force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Campaign__c/Job_Campaign__c.object-meta.xml
<CustomObject>
    <label>Job Campaign</label>
    <nameField>
        <label>Job Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Job_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Job_Campaign__c</fullName>
    <label>Job Campaign</label>
    <referenceTo>Job_Campaign__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CandidateTestDataFactory.cls
public class CandidateTestDataFactory {
	public static List<Candidate__c> createCandidate(Integer candidateCount, String CanidateStatus) {
        Job_Campaign__c j = new Job_Campaign__c();
        j.Name = 'Test job name';
        j.Active__c = true;
        insert j;
        
        Position__c position = new Position__c();
        position.Name = 'Test position name';
        position.Type__c = 'Full Time';
        position.Job_Campaign__c = j.Id;
        insert position;
        
        
        List<Candidate__c> candidates = new List<Candidate__c>();
        for(Integer k = 0; k<candidateCount; k++) {
            Candidate__c cand = new Candidate__c();
            cand.Name = 'Candidate'+k;
            cand.Email__c = 'Candidate'+k+'@test.com';
            cand.Status__c = CanidateStatus;
            cand.Active__c = true;
            cand.Position__c = position.Id;
            candidates.add(cand);
        }
        insert candidates;
        return candidates;
    }
}