force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Body__mdt/Email_Body__mdt.object-meta.xml
<CustomObject>
    <label>Email Body</label>
    <pluralLabel>Email Bodies</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_Body__mdt/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <label>Email Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Campaign__c/Job_Campaign__c.object-meta.xml
<CustomObject>
    <label>Job Campaign</label>
    <nameField>
        <label>Job Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Job_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Job_Campaign__c</fullName>
    <label>Job Campaign</label>
    <referenceTo>Job_Campaign__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Toggle_Settings__c/Toggle_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Toggle Settings</label>
</CustomObject>

force-app/main/default/objects/Toggle_Settings__c/fields/Settings__c.field-meta.xml
<CustomField>
    <fullName>Settings__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Settings</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/JobCampaignAfterTriggerHandler.cls
public class JobCampaignAfterTriggerHandler {
    public void updateCandidateStatus(List<Job_Campaign__c> JobList) {
        //List<Job_Campaign__c> jobs = [Select Id, Job_Campaign__r.active__c from Position__c where Job_Campaign__c in :JobList];
        //List<Candidate__c> candidates = [select active__c, Job_Campaign__r.active__c from Candidate__C where Position__c.Id in :jobList];
        Boolean enableEmail = Toggle_Settings__c.getInstance('EnableEmails').Settings__c;
        Email_Body__mdt activateBody = [Select Email_Body__c from Email_Body__mdt where label = 'Activate Job'];
        Email_Body__mdt deactivateBody = [Select Email_Body__c from Email_Body__mdt where label = 'Deactivate Job'];
        Map<Id, Boolean> positionMap = new Map<Id, Boolean>();
        
        List<Position__c> positions = [Select Id, Job_Campaign__r.active__c from Position__c where Job_Campaign__c in :JobList];
        for(Position__c p : positions) {
            positionMap.put(p.Id, p.Job_Campaign__r.active__c);
        }
        List<Candidate__c> candidates = [select active__c, Status__c, Email__c, Position__r.Id from Candidate__C where Position__c in :positions];
        List<Candidate__c> updatedCandidates = new List<Candidate__c>();
        
        for(Candidate__c c : candidates) {
            if(!positionMap.get(c.Position__r.Id)) {
                c.Status__c = 'On Hold';
                if(enableEmail) {
                    sendEmail(c.Email__c, activateBody.Email_Body__c);
                }
            }
            else if(positionMap.get(c.Position__r.Id) && c.Status__c == 'On Hold') {
                c.Status__c = 'In Progress';                
				if(enableEmail) {
                    sendEmail(c.Email__c, deactivateBody.Email_Body__c);
                }
            }
            updatedCandidates.add(c);
        }
        Database.update(updatedCandidates, false);
        
    }
    
    public void sendEmail(String emailId, String Body) {
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new String[] { emailId };
        message.optOutPolicy = 'FILTER';
        message.subject = 'Job campaign updated';
        message.plainTextBody = body;
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
        Messaging.sendEmail(messages);
		system.debug('email sent');        
    }
}