force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/designation__c/designation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>designation</label>
</CustomObject>

force-app/main/default/objects/designation__c/fields/designation__c.field-meta.xml
<CustomField>
    <fullName>designation__c</fullName>
    <label>designation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PositionAfterTriggerHandler.cls
public class PositionAfterTriggerHandler {
    public void updateCandidateDesignation(List<Position__c> pos) {
        
        List<Candidate__c> candidates = [select Designation__c, Position__r.Assignee__c from Candidate__C where Position__c in :pos];
        system.debug(candidates);
        List<Candidate__c> updatedCandidates = new List<Candidate__c>();
        for(Candidate__c c: candidates) {
            if(c.Position__r.Assignee__c != null) {
                String des = designation__c.getInstance(c.Position__r.Assignee__c).designation__c;
                c.Designation__c = des;
                updatedCandidates.add(c);
            }
        }
        Database.update(updatedCandidates, false);
    }
}