force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Campaign__c/Job_Campaign__c.object-meta.xml
<CustomObject>
    <label>Job Campaign</label>
    <nameField>
        <label>Job Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Job_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Job_Campaign__c</fullName>
    <label>Job Campaign</label>
    <referenceTo>Job_Campaign__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Toggle_Settings__c/Toggle_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Toggle Settings</label>
</CustomObject>

force-app/main/default/objects/Toggle_Settings__c/fields/Settings__c.field-meta.xml
<CustomField>
    <fullName>Settings__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Settings</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/JobCampaignAfterTriggerTest.cls
@isTest
public class JobCampaignAfterTriggerTest {
    static testMethod void testUpdateCandidateStatusNonActive() {
        List<Job_Campaign__c> jobs = TestDataFactory.createActiveInactiveJobCampaignAndCandidates(true, 5, 'In Progress');
        List<Job_Campaign__c> updatedJobs = new List<Job_Campaign__c>();
        for(Job_Campaign__c j: jobs) {
            j.Active__c = false;
            updatedJobs.add(j);
        }
        System.debug('Updated jobs - '+updatedJobs);
        Test.startTest();
        update updatedJobs;
        Test.stopTest();
        
        List<Position__c> pos = [Select Id, (Select Id, status__c from Candidates__r) from Position__c where Job_Campaign__c in :jobs];
        for(Position__c pp: pos) {
            for(Candidate__c c: pp.Candidates__r) {
            	system.assertEquals('On Hold', c.Status__c);
            }
        }
        
    }
    
    static testMethod void testUpdateCandidateStatusActive() {
        List<Job_Campaign__c> jobs = TestDataFactory.createActiveInactiveJobCampaignAndCandidates(false, 5, 'On Hold');
        List<Job_Campaign__c> updatedJobs = new List<Job_Campaign__c>();
        for(Job_Campaign__c j: jobs) {
            j.Active__c = true;
            updatedJobs.add(j);
        }
        Test.startTest();
        update updatedJobs;
        Test.stopTest();
        
        List<Position__c> pos = [Select Id, (Select Id, status__c from Candidates__r) from Position__c where Job_Campaign__c in :jobs];
        for(Position__c pp: pos) {
            for(Candidate__c c: pp.Candidates__r) {
            	system.assertEquals('In Progress', c.Status__c);
            }
        }
    }
    
    Static testMethod void testDisabledTrigger() {
        insert new Toggle_Settings__c(Name = 'EnableAfterUpdateTrigger', Settings__c = false);
        List<Job_Campaign__c> jobs = TestDataFactory.createActiveInactiveJobCampaignAndCandidates(false, 5, 'On Hold');
        List<Job_Campaign__c> updatedJobs = new List<Job_Campaign__c>();
        for(Job_Campaign__c j: jobs) {
            j.Active__c = true;
            updatedJobs.add(j);
        }
        Test.startTest();
        update updatedJobs;
        Test.stopTest();
    }
}