force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Campaign__c/Job_Campaign__c.object-meta.xml
<CustomObject>
    <label>Job Campaign</label>
    <nameField>
        <label>Job Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Job_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Job_Campaign__c</fullName>
    <label>Job Campaign</label>
    <referenceTo>Job_Campaign__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Toggle_Settings__c/Toggle_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Toggle Settings</label>
</CustomObject>

force-app/main/default/objects/Toggle_Settings__c/fields/Settings__c.field-meta.xml
<CustomField>
    <fullName>Settings__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Settings</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Job_Campaign__c> createActiveInactiveJobCampaignAndCandidates(Boolean active, Integer count, String CanidateStatus) {
        insert new Toggle_Settings__c(Name = 'EnableEmails', Settings__c = true);
        insert new Toggle_Settings__c(Name = 'EnableAfterUpdateTrigger', Settings__c = true);
        List<Job_Campaign__c> jobs = new List<Job_Campaign__c>();
        for(Integer i=1; i<= count; i++) {
            Job_Campaign__c j = new Job_Campaign__c();
            j.Name = 'job'+i;
            j.Active__c = active;
            jobs.add(j);
        }
        insert jobs; 
        List<Position__c> pos = new List<Position__c>();
        for(Job_Campaign__c j: jobs) {
            for(Integer k=1; k<= count; k++) {
                pos.add(createPosition(j, k));
            }
        }
        insert pos;
        List<Candidate__c> candidates = new List<Candidate__c>();
        for(Position__c p: pos) {
            for(Integer k=1; k<= count; k++) {
                candidates.add(createCandidate(p , k, CanidateStatus));
            }
        }
        insert candidates;
        return jobs;
    }
    
    static Position__c createPosition(Job_Campaign__c job, Integer i) {
        Position__c position = new Position__c();
        position.Name = job.Name+'Position'+i;
        position.Type__c = 'Full Time';
        position.Job_Campaign__c = job.Id;
        return position;
    }
    
    static Candidate__c createCandidate(Position__c pos, Integer i, String CanidateStatus) {
        Candidate__c cand = new Candidate__c();
        cand.Name = pos.Name+'Candidate'+i;
        cand.Email__c = pos.Name+'Candidate'+i+'@example.com';
        cand.Status__c = CanidateStatus;
        cand.Active__c = true;
        cand.Position__c = pos.Id;
        return cand;
    }
    
}