force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Minimum_Wage__c/Minimum_Wage__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Minimum Wage</label>
</CustomObject>

force-app/main/default/objects/Minimum_Wage__c/fields/MinWage__c.field-meta.xml
<CustomField>
    <fullName>MinWage__c</fullName>
    <label>MinWage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CandidateAfterTriggerHandler.cls
public class CandidateAfterTriggerHandler {
    public void updateCandidateMinWage(List<Candidate__c> candidates) {
        for(Candidate__c c: candidates) {
            if(c.Status__c == 'Hired') {
                String year = String.valueOf(System.today().year()); 
                Integer minWage = Integer.valueOf(Minimum_Wage__c.getInstance(year).MinWage__c);
                If(minWage != null) {
                	c.MinWage__c = minWage;
                }
            }
        }
    }
}