force-app/main/default/objects/Job_Campaign__c/Job_Campaign__c.object-meta.xml
<CustomObject>
    <label>Job Campaign</label>
    <nameField>
        <label>Job Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Job_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Job_Campaign__c</fullName>
    <label>Job Campaign</label>
    <referenceTo>Job_Campaign__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FutureMethod.cls
public class FutureMethod {
	@future
    public static void addPositions(List<ID> ids) {
        List<Job_Campaign__c> jobs = [Select ID, Name from Job_Campaign__c where Id in :ids];
        List<Position__c> pos = new List<Position__c>();
        for(Job_Campaign__c j : jobs) {
            Position__c p = new Position__c();
            p.Name = j.Name+'-Developer';
            p.Type__c = 'Full Time';
            p.Job_Campaign__c = j.Id;
         	pos.add(p);
        }
        DataBase.insert(pos, false);

    }
}