force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flat__c/Flat__c.object-meta.xml
<CustomObject>
    <label>Flat</label>
    <nameField>
        <label>Flat Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flat__c/fields/Building_Name__c.field-meta.xml
<CustomField>
    <fullName>Building_Name__c</fullName>
    <label>Building Name</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Flats</relationshipLabel>
    <relationshipName>Flats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BuildingTriggerHandler.cls
public class BuildingTriggerHandler {
    public void updateAddress(List<Building__c> buildingList) {
        List<Flat__c> updatedFlats = new List<Flat__c>();
        List<Id> ids = new List<Id>();
        for(Building__c buil: buildingList) {
            ids.add(buil.Id);
        }
        List<Building__c> buildings = [Select Id, Address__c, (Select Name, Address__c from Flats__r) from Building__c where Id in :ids];
        for(Building__c bb: buildings) {
            for(Flat__c ff: bb.flats__r) {
                ff.Address__c = bb.Address__c;
                updatedFlats.add(ff);
            }
        }
        update updatedFlats;
    }
}